// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using training_project.Models.Context;

namespace training_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210416063836_Folder-file")]
    partial class Folderfile
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("training_project.Models.File", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("createAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("folderid")
                        .HasColumnType("int");

                    b.Property<string>("modifedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("folderid");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("training_project.Models.Folder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("createAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("folderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modifedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("parentID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("parentID");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("training_project.Models.File", b =>
                {
                    b.HasOne("training_project.Models.Folder", "folder")
                        .WithMany()
                        .HasForeignKey("folderid");

                    b.Navigation("folder");
                });

            modelBuilder.Entity("training_project.Models.Folder", b =>
                {
                    b.HasOne("training_project.Models.Folder", null)
                        .WithMany("subFolders")
                        .HasForeignKey("parentID");
                });

            modelBuilder.Entity("training_project.Models.Folder", b =>
                {
                    b.Navigation("subFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
